spring.application.name=demo_one
server.port=8085
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto= update
spring.jpa.generate-ddl =true
spring.jpa.show-sql=true



spring.data.redis.host=redis-16352.c73.us-east-1-2.ec2.cloud.redislabs.com
spring.data.redis.port=16352
spring.cache.type=redis
spring.data.redis.password=ssuDFjDFEZMpiwu9Fs3olAuYZxgljK7Z
spring.cache.redis.time-to-live=600000